export {
  SITE_URL,
  SITE_NAME,
  SITE_TITLE,
  SITE_DESCRIPTION,
  BRAND_KEYWORDS,
  CORE_SERVICE_KEYWORDS,
  INSURANCE_TYPE_KEYWORDS,
  CLAIM_ISSUE_KEYWORDS,
  PERSONA_KEYWORDS,
  INDUSTRY_KEYWORDS,
  QUESTION_KEYWORDS,
  LOCATION_KEYWORDS,
  INSURER_KEYWORDS,
  COMMERCIAL_INTENT_KEYWORDS,
  LONG_TAIL_KEYWORDS,
  SITE_KEYWORDS,
  PUBLIC_ROUTES,
  PUBLIC_ROUTE_PATHS,
} from "@/content/seo";

export { BUSINESS_DETAILS, LEADERSHIP } from "@/content/business";
export { MARKETING_PAGES } from "@/content/marketing";
