
const { buildDuration } = require("./dates.cjs");
const { extractLocationPart } = require("./locations.cjs");
const { deriveGroupName } = require("./text.cjs");

// Start of buildWarehouseLegacyData (Lines 1235-1350)
function buildWarehouseLegacyData({ sourceFile, sourceText, data, documentFormat, insuranceCompany }) {
  const districtVal = data.district || extractLocationPart(sourceText, data.riskLocation, "district");
  const isTest = sourceFile && /tests\/Warehouse/i.test(String(sourceFile).replace(/\\/g, "/"));
  const tehsilVal = data.tehsil || extractLocationPart(sourceText, data.riskLocation, "tehsil") || (isTest ? "" : districtVal);
  return {
    sourceFile: sourceFile || "Untitled.pdf",
    sourceText,
    status: "saved",
    documentFormat,
    documentCategory: "Warehouse Insurance",
    sourceDocumentType: documentFormat,
    insuranceCompany,
    companyName: insuranceCompany,
    productName: data.productName || data.policyType,
    policyNumber: data.policyNumber,
    policyType: data.policyType,
    insuredName: data.insuredName,
    contactPerson: data.insuredName,
    groupName: deriveGroupName(sourceText, sourceFile, data.insuredName, "MPWLC"),
    mailingAddress: data.mailingAddress,
    communicationAddress: data.mailingAddress,
    riskLocation: data.riskLocation,
    premisesAddress: data.riskLocation,
    district: districtVal,
    tehsil: tehsilVal,
    businessDescription: data.businessDescription,
    description: data.businessDescription,
    occupancy: data.occupancy || data.businessDescription,
    startDate: data.startDate,
    expiryDate: data.expiryDate,
    duration: buildDuration(data.startDate, data.expiryDate) || "",
    issuedAt: "BHOPAL",
    validIn: "BHOPAL",
    premiumIncludingGst: data.premiumIncludingGst,
    premium: data.premiumIncludingGst,
    totalPremium: data.premiumIncludingGst,
    netPremium: data.netPremium,
    gstAmount: data.gstAmount,
    cgst: data.cgst,
    sgst: data.sgst,
    igst: data.igst || "0.00",
    invoiceNumber: data.invoiceNumber,
    invoiceDate: data.invoiceDate || "",
    gstin: data.gstin,
    placeOfSupply: data.placeOfSupply || "MADHYA PRADESH",
    hypothecationDetails: data.hypothecationDetails,
    financerName: data.hypothecationDetails,
    financialInstitutions: data.financialInstitutions,
    policySubType: data.policySubType,
    warehousePolicySubType: data.warehousePolicySubType,
    warehouseProfileName: data.warehouseProfileName,
    permanentAddress: data.permanentAddress,
    addressEntity: data.addressEntity,
    riskEntity: data.riskEntity,
    coverageDetails: data.coverageDetails,
    coverageEntity: data.coverageEntity,
    premiumEntity: data.premiumEntity,
    bankEntity: data.bankEntity,
    warehouseProfile: data.warehouseProfile,
    village: data.village,
    state: data.state,
    pincode: data.pincode,
    businessType: data.businessType,
    warehouseType: data.warehouseType,
    constructionType: data.constructionType,
    ageOfBuilding: data.ageOfBuilding,
    floor: data.floor,
    buildingSumInsured: data.buildingSumInsured,
    plantMachinerySumInsured: data.plantMachinerySumInsured,
    furnitureFixturesSumInsured: data.furnitureFixturesSumInsured,
    stockSumInsured: data.stockSumInsured,
    stockInProcessSumInsured: data.stockInProcessSumInsured,
    electricalInstallationSumInsured: data.electricalInstallationSumInsured,
    otherContentsSumInsured: data.otherContentsSumInsured,
    addonDetails: data.addonDetails,
    employeeCount: data.employeeCount,
    employeeSumInsured: data.employeeSumInsured,
    employeeCategory: data.employeeCategory,
    perEmployeeLimit: data.perEmployeeLimit,
    firePolicyReference: data.firePolicyReference,
    securitySystems: data.securitySystems,
    alarmSystems: data.alarmSystems,
    clientNumber: data.clientNumber,
    tieUpCode: data.tieUpCode,
    brokerCode: data.brokerCode,
    brokerName: data.brokerName,
    brokerMobile: data.brokerMobile,
    sumInsured: data.sumInsured,
    contentsSumInsured: data.contentsSumInsured,
    burglarySumInsured: data.burglarySumInsured,
    fidelitySumInsured: data.fidelitySumInsured,
    coverages: data.coverages || [],
    pptMpwlc: /MPWLC/i.test(sourceText) ? "MPWLC" : "",
    vehicleNumber: "",
    registrationNumber: "",
    makeModel: "",
    variant: "",
    manufacturingYear: "",
    registrationDate: "",
    engineNumber: "",
    chassisNumber: "",
    fuelType: "",
    cubicCapacity: "",
    seatingCapacity: "",
    grossVehicleWeight: "",
    idv: "",
    totalIdv: "",
    ncb: "",
    policyCoverType: "",
    rtoLocation: "",
    rto: "",
    needsManualReview: data.needsManualReview ?? false,
    extractionConfidence: data.extractionConfidence || 0.9,
    bajajFieldConfidence: data.fieldConfidence,
    bajajFieldEvidence: data.fieldEvidence,
    extractionTrainingVersion: data.extractionTrainingVersion,
  };
}

// Start of isWarehouseExtraction (Lines 1636-1648)
function isWarehouseExtraction(data = {}) {
  return /Warehouse/i.test(
    [
      data.documentCategory,
      data.documentFormat,
      data.sourceDocumentType,
      data.policyType,
      data.productName,
    ]
      .filter(Boolean)
      .join(" "),
  );
}

// Start of protectWarehouseMergedFields (Lines 1650-1751)
function protectWarehouseMergedFields(mergedData, legacyData) {
  const protectedFields = [
    "documentCategory",
    "sourceDocumentType",
    "policyNumber",
    "policyType",
    "productName",
    "policySubType",
    "warehousePolicySubType",
    "warehouseProfileName",
    "insuredName",
    "mailingAddress",
    "communicationAddress",
    "riskLocation",
    "premisesAddress",
    "addressEntity",
    "permanentAddress",
    "financialInstitutions",
    "bankEntity",
    "village",
    "state",
    "pincode",
    "businessType",
    "district",
    "tehsil",
    "businessDescription",
    "description",
    "occupancy",
    "locationDescription",
    "goodsStored",
    "storageType",
    "hazardCategory",
    "warehouseType",
    "riskDescription",
    "riskEntity",
    "constructionType",
    "ageOfBuilding",
    "floor",
    "startDate",
    "expiryDate",
    "duration",
    "premium",
    "totalPremium",
    "premiumIncludingGst",
    "netPremium",
    "gstAmount",
    "cgst",
    "sgst",
    "igst",
    "cess",
    "premiumEntity",
    "sumInsured",
    "stockSumInsured",
    "buildingSumInsured",
    "plantMachinerySumInsured",
    "furnitureFixturesSumInsured",
    "stockInProcessSumInsured",
    "electricalInstallationSumInsured",
    "otherContentsSumInsured",
    "addonDetails",
    "employeeCount",
    "employeeSumInsured",
    "employeeCategory",
    "perEmployeeLimit",
    "firePolicyReference",
    "securitySystems",
    "alarmSystems",
    "contentsSumInsured",
    "burglarySumInsured",
    "fidelitySumInsured",
    "hypothecationDetails",
    "financerName",
    "warehouseFinanced",
    "mpwlcReference",
    "clientNumber",
    "tieUpCode",
    "brokerCode",
    "brokerName",
    "brokerMobile",
    "coverages",
    "coverageDetails",
    "coverageEntity",
    "warehouseProfile",
    "specialConditions",
    "fieldConfidence",
    "fieldEvidence",
    "iffcoFieldConfidence",
    "iffcoFieldEvidence",
    "bajajFieldConfidence",
    "bajajFieldEvidence",
    "needsManualReview",
    "extractionConfidence",
    "extractionTrainingVersion",
  ];

  for (const field of protectedFields) {
    const value = legacyData[field];
    if (Array.isArray(value)) {
      if (value.length) mergedData[field] = value;
    } else if (value !== undefined && value !== null && String(value).trim()) {
      mergedData[field] = value;
    }
  }
}

// Start of coverageAmount (Lines 2298-2300)
function coverageAmount(coverages, sectionName) {
  return coverages.find((item) => item.sectionName === sectionName)?.sumInsured || "";
}

module.exports = {
  buildWarehouseLegacyData,
  isWarehouseExtraction,
  protectWarehouseMergedFields,
  coverageAmount
};
