// app/ui/dashboard/constants.js
import {
  BarChart3,
  Edit3,
  FileCog,
  FileText,
  Settings,
  Upload,
  Users,
  RefreshCw,
} from "lucide-react";

export const NAV_ITEMS = [
  { id: "bulk-entry", label: "Bulk PDF Upload", icon: Upload },
  { id: "manual-entry", label: "Manual Policy Entry", icon: Edit3 },
  { id: "records", label: "Policy Records", icon: FileText },
  { id: "customers", label: "Customer Management", icon: Users },
  { id: "renewals", label: "Renewals", icon: RefreshCw },
  { id: "analytics", label: "Analytics & Reports", icon: BarChart3 },
  { id: "field-setup", label: "Field Setup", icon: FileCog },
  { id: "settings", label: "Settings", icon: Settings },
  { id: "user-management", label: "User Management", icon: Users, roles: ["SUPER_ADMIN", "ADMIN", "MANAGER"] },
];

export const EMPTY_FORM = {
  srNo: "",
  sourceFile: "",
  status: "pending",
  insuredName: "",
  policyNumber: "",
  contactNumber: "",
  contactPerson: "",
  whatsappGroupName: "",
  groupName: "",
  policyType: "",
  premium: "",
  totalPremium: "",
  netPremium: "",
  tpDriverOwner: "",
  odPremium: "",
  dueCollection: "",
  collectedAmount: "",
  modeOfPayment: "",
  remark: "",
  sumInsured: "",
  startDate: "",
  expiryDate: "",
  duration: "",
  riskLocation: "",
  district: "",
  tehsil: "",
  insuranceCompany: "",
  description: "",
  pptMpwlc: "",
  occupancy: "",
  validIn: "",
  vehicleNumber: "",
  registrationNumber: "",
  makeModel: "",
  variant: "",
  manufacturingYear: "",
  registrationDate: "",
  engineNumber: "",
  chassisNumber: "",
  fuelType: "",
  cubicCapacity: "",
  seatingCapacity: "",
  grossVehicleWeight: "",
  idv: "",
  ncb: "",
  policyCoverType: "",
  rtoLocation: "",
  nomineeName: "",
  financerName: "",
};

export const FIELD_SETUP = [
  ["Sr No", "srNo"],
  ["Insured Name", "insuredName"],
  ["Policy Number", "policyNumber"],
  ["Contact Number", "contactNumber"],
  ["Contact Person", "contactPerson"],
  ["WhatsApp Group Name", "whatsappGroupName"],
  ["Group Name", "groupName"],
  ["Policy Type", "policyType"],
  ["Premium", "premium"],
  ["Total Premium", "totalPremium"],
  ["Net Premium", "netPremium"],
  ["TP + Driver + Owner", "tpDriverOwner"],
  ["OD Premium", "odPremium"],
  ["Due Collection", "dueCollection"],
  ["Collected Amount", "collectedAmount"],
  ["Mode Of Payment", "modeOfPayment"],
  ["Remark", "remark"],
  ["Sum Insured", "sumInsured"],
  ["Start Date", "startDate"],
  ["Expiry Date", "expiryDate"],
  ["Duration", "duration"],
  ["Risk Location", "riskLocation"],
  ["District", "district"],
  ["Tehsil", "tehsil"],
  ["Insurance Company", "insuranceCompany"],
  ["Description", "description"],
  ["PPT / MPWLC", "pptMpwlc"],
  ["Occupancy", "occupancy"],
  ["Valid In", "validIn"],
];
