export const OPERATIONS_MODULES = [
  {
    id: "work-center",
    name: "Work Center",
    description: "Plan tasks, reminders, approvals, escalations, and team workload.",
    route: "/work-center",
    buttonLabel: "Open Work Center",
    accent: "blue",
    functions: [
      "Task management",
      "Follow-up planner",
      "Renewal reminders",
      "Approvals",
      "Escalations",
      "Activity feed",
    ],
  },
  {
    id: "lead-generation",
    name: "Lead Generation",
    description: "Capture lead requirements before policy recommendation.",
    route: "/operations/lead-generation",
    buttonLabel: "Open Lead Generation",
    accent: "green",
    functions: [
      "Create lead profile",
      "Record insurance needs",
      "Existing policy details",
      "Risk assessment",
      "Family information",
      "Income information",
      "Future insurance requirements",
      "Lead qualification",
    ],
  },
  {
    id: "manual-policy-entry",
    name: "Manual Policy Entry",
    description: "Create policy records manually when PDF extraction is unavailable.",
    route: "/operations/manual-policy-entry",
    buttonLabel: "Open Policy Entry",
    accent: "blue",
    functions: ["Manual policy creation", "Policy editing", "Data verification", "Policy upload support"],
  },
  {
    id: "claims-management",
    name: "Claims Management",
    description: "Manage customer claims and claim servicing.",
    route: "/operations/claims-management",
    buttonLabel: "Open Claims",
    accent: "red",
    functions: [
      "Register claim",
      "Track claim status",
      "Upload claim documents",
      "Surveyor information",
      "Settlement tracking",
      "Rejection tracking",
    ],
  },
  {
    id: "declarations",
    name: "Declarations",
    description: "Manage customer declarations and compliance documents.",
    route: "/operations/declarations",
    buttonLabel: "Open Declarations",
    accent: "purple",
    functions: [
      "Health declarations",
      "Risk declarations",
      "Business declarations",
      "Proposal declarations",
      "Declaration history",
    ],
  },
  {
    id: "endorsements",
    name: "Endorsements",
    description: "Manage policy modifications and endorsements.",
    route: "/dashboard/endorsements",
    buttonLabel: "Open Endorsements",
    accent: "amber",
    functions: [
      "Address changes",
      "Nominee changes",
      "Vehicle changes",
      "Coverage updates",
      "Policy corrections",
    ],
  },
  {
    id: "service-requests",
    name: "Service Requests",
    description: "Handle customer servicing requests.",
    route: "/operations/service-requests",
    buttonLabel: "Open Service Requests",
    accent: "cyan",
    functions: [
      "Policy copy requests",
      "Renewal support",
      "Premium certificates",
      "NCB certificates",
      "Customer support tickets",
      "General servicing",
    ],
  },
  {
    id: "lead-management",
    name: "Lead Management",
    description: "Manage insurance sales opportunities and prospects.",
    route: "/operations/lead-management",
    buttonLabel: "Open Lead Management",
    accent: "indigo",
    functions: [
      "Lead creation",
      "Lead assignment",
      "Follow-ups",
      "Opportunity tracking",
      "Lead conversion tracking",
      "Lost lead tracking",
    ],
  },
  {
    id: "birthday-management",
    name: "Birthday Management",
    description: "Track and manage client birthdays, download import templates, import/export birthday lists, and send greetings.",
    route: "/operations/birthday-management",
    buttonLabel: "Open Birthday Management",
    accent: "pink",
    functions: [
      "Track upcoming birthdays",
      "Download import template",
      "Import client birthdays",
      "Export birthday list",
      "Filter by month/date range",
      "WhatsApp greeting templates",
    ],
  },
  {
    id: "whatsapp-setup",
    name: "WhatsApp Setup",
    description: "Manage self-hosted OpenWA API connection status, QR code scanning, message queue, logs, and template editing.",
    route: "/operations/whatsapp-setup",
    buttonLabel: "Open WhatsApp Setup",
    accent: "indigo",
    functions: [
      "OpenWA server status",
      "QR code scanner",
      "Template editor",
      "Message logs",
      "Test message tool",
      "Queue manager",
    ],
  },
  {
    id: "client-management",
    name: "Client Management",
    description: "Manage client access portals, view Client IDs, configure Client MPINs, and manage credentials.",
    route: "/operations/client-management",
    buttonLabel: "Open Client Management",
    accent: "emerald",
    functions: [
      "View Client ID",
      "Configure Client MPIN",
      "Create new client login",
      "Search client list",
      "Update profile phone/email",
    ],
  },
];

export const FUTURE_OPERATIONS_MODULES = [
  "Proposal Management",
  "Quotations",
  "KYC Verification",
  "Document Collection",
  "Inspections",
  "Field Visits",
  "Agent Activities",
  "Customer Support Center",
  "Task Management",
  "Workflow Automation",
];

export function getOperationsModule(id) {
  return OPERATIONS_MODULES.find((module) => module.id === id) || null;
}
